import {
  Star, Heart, Lightbulb, Bookmark, Flag, Fire, Rocket, Brain,
  Gear, Smiley, Target, Clock, MapPin, Trophy, MusicNote,
  Camera, ChatCircle, CheckCircle, Question, WarningCircle,
  House, User, Book, Pencil, Envelope, Phone, Calendar,
  Sun, Moon, Cloud, Palette, Leaf, Flower, Coffee,
  ThumbsUp, Eye, Bell, Lock, Key, Compass,
  MagnifyingGlass, GlobeSimple, Crown, Diamond, Cube,
  Megaphone, Butterfly,
} from "@phosphor-icons/react";

export const ICON_MAP = {
  star: Star,
  heart: Heart,
  lightbulb: Lightbulb,
  bookmark: Bookmark,
  flag: Flag,
  fire: Fire,
  rocket: Rocket,
  brain: Brain,
  gear: Gear,
  smiley: Smiley,
  target: Target,
  clock: Clock,
  mappin: MapPin,
  trophy: Trophy,
  musicnote: MusicNote,
  camera: Camera,
  chatcircle: ChatCircle,
  checkcircle: CheckCircle,
  question: Question,
  warning: WarningCircle,
  house: House,
  user: User,
  book: Book,
  pencil: Pencil,
  envelope: Envelope,
  phone: Phone,
  calendar: Calendar,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  palette: Palette,
  leaf: Leaf,
  flower: Flower,
  coffee: Coffee,
  thumbsup: ThumbsUp,
  eye: Eye,
  bell: Bell,
  lock: Lock,
  key: Key,
  compass: Compass,
  search: MagnifyingGlass,
  globe: GlobeSimple,
  crown: Crown,
  diamond: Diamond,
  cube: Cube,
  megaphone: Megaphone,
  butterfly: Butterfly,
};

export const ICON_LIST = Object.entries(ICON_MAP).map(([key, Icon]) => ({ key, Icon }));
